from .client import SDK_VERSION as __version__
from .client import ReplayStack, ReplayStackClient
from .context import (
    add_breadcrumb,
    add_context_breadcrumb,
    clear_breadcrumbs,
    clear_context_breadcrumbs,
    get_breadcrumbs,
    get_context_breadcrumbs,
    run_with_replaystack_context,
)
from .runtime import install_replaystack_process_guards
from .stacktrace import format_exception, parse_exception_stack, parse_stack_trace
from .types import (
    AuthMode,
    Breadcrumb,
    CaptureResponse,
    EventStatus,
    EventType,
    LogLevel,
    ReplayStackConfig,
    ReplayStackEvent,
    ReplayStackLog,
    StackFrame,
)
from .utils import (
    build_absolute_request_url_from_parts,
    create_trace_id,
    detect_auth_mode,
    get_error_details,
    headers_to_object,
    mask_data,
    mask_sensitive_data,
    normalize_absolute_request_url,
    normalize_endpoint,
    safe_json_clone,
    safe_stringify,
    should_ignore_path,
    should_sample,
    sleep_seconds,
    truncate_payload,
    truncate_utf8_string,
)

__all__ = [
    "__version__",
    "AuthMode",
    "Breadcrumb",
    "CaptureResponse",
    "EventStatus",
    "EventType",
    "LogLevel",
    "ReplayStack",
    "ReplayStackClient",
    "ReplayStackConfig",
    "ReplayStackEvent",
    "ReplayStackLog",
    "StackFrame",
    "add_breadcrumb",
    "add_context_breadcrumb",
    "build_absolute_request_url_from_parts",
    "clear_breadcrumbs",
    "clear_context_breadcrumbs",
    "create_trace_id",
    "detect_auth_mode",
    "format_exception",
    "get_breadcrumbs",
    "get_context_breadcrumbs",
    "get_error_details",
    "headers_to_object",
    "install_replaystack_process_guards",
    "mask_data",
    "mask_sensitive_data",
    "normalize_absolute_request_url",
    "normalize_endpoint",
    "parse_exception_stack",
    "parse_stack_trace",
    "run_with_replaystack_context",
    "safe_json_clone",
    "safe_stringify",
    "should_ignore_path",
    "should_sample",
    "sleep_seconds",
    "truncate_payload",
    "truncate_utf8_string",
]
